### ISSUE TITLE
seg fault from xlink-assign-ions

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#365]
This one is simple to explain:

/net/noble/vol1/home/noble/proj/crux/crux-toolkit/src/crux xlink-assign-ions KNIEFFEAR RAELEAKLAEVLAAANAR 1 7 136.100049 5 1 better3.mgf
INFO: Beginning xlink-assign-ions.
INFO: Parser could not determine scan numbers for this file, using ordinal numbers as scan numbers.
WARNING: Proteowizard parser could not determine scan numbers for this file. Assigning new scan numbers.
./runall: line 32: 20874 Segmentation fault      (core dumped) 
[xlink-assign-ion-bug.zip](https://github.com/crux-toolkit/crux-toolkit/files/814026/xlink-assign-ion-bug.zip)

**Comment by kaipot** [comment]
I need to look a bit at what the code is supposed to be doing. Here is the trace:

```
#0  0x00000000009d85fa in Crux::Peptide::copyPtr (this=0x0) at /home/kaipo/documents/crux2/src/model/Peptide.cpp:52
#1  0x000000000085c31a in XLinkablePeptide::XLinkablePeptide (this=0x1b48c00, xlinkablepeptide=...)
    at /home/kaipo/documents/crux2/src/app/xlink/XLinkablePeptide.cpp:62
#2  0x000000000084e195 in __gnu_cxx::new_allocator<XLinkablePeptide>::construct (this=0x1b4d598, __p=0x1b48c00, __val=...)
    at /usr/include/c++/4.8.2/ext/new_allocator.h:130
#3  0x000000000084bba3 in __gnu_cxx::__alloc_traits<std::allocator<XLinkablePeptide> >::construct<XLinkablePeptide> (__a=..., __p=0x1b48c00, __arg=...)
    at /usr/include/c++/4.8.2/ext/alloc_traits.h:216
#4  0x000000000084bd5d in std::vector<XLinkablePeptide, std::allocator<XLinkablePeptide> >::_M_insert_aux (this=0x1b4d598,
    __position=<error reading variable: Cannot access memory at address 0x0>, __x=...) at /usr/include/c++/4.8.2/bits/vector.tcc:353
#5  0x000000000084a10c in std::vector<XLinkablePeptide, std::allocator<XLinkablePeptide> >::push_back (this=0x1b4d598, __x=...)
    at /usr/include/c++/4.8.2/bits/stl_vector.h:913
#6  0x000000000086494e in XLinkPeptide::XLinkPeptide (this=0x1b4d340, peptideA=0x172c370 "KNIEFFEAR", peptideB=0x1731160 "RAELEAKLAEVLAAANAR", posA=0, posB=6)
    at /home/kaipo/documents/crux2/src/app/xlink/XLinkPeptide.cpp:69
#7  0x000000000083d54a in XLinkAssignIons::main (this=0x172e900, argc=11, argv=0x7fffffffe480)
    at /home/kaipo/documents/crux2/src/app/xlink/xlink_assign_ions.cpp:91
#8  0x000000000094bb4c in CruxApplicationList::main (this=0x7fffffffe2d0, argc=12, argv=0x7fffffffe478)
    at /home/kaipo/documents/crux2/src/app/CruxApplicationList.cpp:220
#9  0x000000000082ee3d in main (argc=12, argv=0x7fffffffe478) at /home/kaipo/documents/crux2/src/crux-main.cpp:105
```

It starts from xlink_assign_ions.cpp:91
```
xlp = new XLinkPeptide(peptideA, peptideB, posA-1, posB-1);
```

The XLinkPeptide constructor tries to create an XLinkablePeptide, but crashes in the constructor. I can fix it by changing
```
peptide_ = xlinkablepeptide.peptide_->copyPtr();
```
to
```
sequence_ = xlinkablepeptide.sequence_;
if (xlinkablepeptide.peptide_) {
  peptide_ = xlinkablepeptide.peptide_->copyPtr();
}
```

but then I get "FATAL: Internal Error: mass not calculated yet! 1"
